language: java

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8.3

script: "mvn -B clean install"

after_success:
  - bash <(curl -s https://codecov.io/bash)
