version: '{build}'
init:
- ps: "Add-Type -AssemblyName System.IO.Compression.FileSystem\nif (!(Test-Path -Path \"C:\\apache-maven\" )) {\n        Write-Host \"Downloading Maven $env:MAVEN_VERSION\"\n        (new-object System.Net.WebClient).DownloadFile(\"https://repo1.maven.org/maven2/org/apache/maven/apache-maven/$env:MAVEN_VERSION/apache-maven-$env:MAVEN_VERSION-bin.zip\", \"C:\\apache-maven-$env:MAVEN_VERSION-bin.zip\") \n        [System.IO.Compression.ZipFile]::ExtractToDirectory(\"C:\\apache-maven-$env:MAVEN_VERSION-bin.zip\", \"C:\\apache-maven\")\n      }"
environment:
  MAVEN_VERSION: 3.5.4
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
install:
- cmd: >-
    choco install codecov

    choco upgrade codecov

    SET M2_HOME=C:\apache-maven\apache-maven-%MAVEN_VERSION%

    SET PATH=%M2_HOME%\bin;%JAVA_HOME%\bin;%PATH%

    mvn --version
cache:
- C:\apache-maven -> appveyor.yml
- C:\Users\appveyor\.m2 -> pom.xml
- C:\ProgramData\chocolatey
build_script:
- ps: mvn -B clean install
on_success:
- ps: codecov -f target/site/jacoco/jacoco.xml
